clc;
clear all;
close all;
Imin = imread('068.pgm');
Imin2 = imread('079.pgm');
Imcomp = imcomplement(Imin);
Imcomp2 = imcomplement(Imin2);
lev = graythresh(Imcomp);
lev2 = graythresh(Imcomp2);
str = strel('sphere',5);
str2 = strel('square',3);
str3 = strel('line',30,0);
BW = im2bw(Imcomp,lev);
BW5 = im2bw(Imcomp2,lev);
Imfil = imfill(BW,'holes');
Imopen = imopen(Imfil,str);
Imop = imclose(BW5,str3);
BW2 = BW - Imopen;
BW3 = imopen(BW2,str2);
imfil2 = imfill(Imop,'holes');
Imboucl = imopen(imfil2,str);
BW6 = BW5 - Imboucl;
subplot(2,2,1);
imshow(BW6);
title('resultat soustraction 8');
subplot(2,2,2);
imshow(BW2);
title('resultat soustraction 7');
