clc;
clear all;
close all;
Imin = imread('106.pgm');
Imin2 = imread('106.pgm');
Imcomp = imcomplement(Imin);
Imcomp2 = imcomplement(Imin2);
lev = graythresh(Imcomp);
lev2 = graythresh(Imcomp2);
str = strel('disk',4);
str2 = strel('square',2);
str3 = strel('line',25,0);
BW = im2bw(Imcomp,lev);
BW5 = im2bw(Imcomp2,lev);
BW = imclose(BW,str3);
Imfil = imfill(BW,'holes');
Imopen = imopen(Imfil,str);
Imop = imclose(BW5,str);
BW2 = BW - Imopen;
BW3 = imopen(BW2,str);
imfil2 = imfill(Imop,'holes');
imope = imopen(Imfil,str);
BW6 = BW5 - imope;
BW6 = imopen(BW6,str2);
subplot(2,2,1);
imshow(Imfil);
title('Chiffre 5 rempli');
subplot(2,2,2);
imshow(BW6);
title('Top hat chiffre 5');